FROM public.ecr.aws/lambda/python:3.12

# Set lambda root as working directory
WORKDIR ${LAMBDA_TASK_ROOT}

# Install chrome dependencies
RUN dnf install -y atk cups-libs gtk3 libXcomposite alsa-lib \
    libXcursor libXdamage libXext libXi libXrandr libXScrnSaver \
    libXtst pango at-spi2-atk libXt xorg-x11-server-Xvfb \
    xorg-x11-xauth dbus-glib dbus-glib-devel nss mesa-libgbm jq unzip

# Run chrome installer script
COPY chrome-installer.sh .
RUN bash ./chrome-installer.sh

RUN PATH=/opt/chrome-driver:$PATH

# Grab requirement file and install
COPY requirements.txt  .
RUN  pip3 install -r requirements.txt

# Copy everything else
COPY . .

CMD [ "etl.handler" ]
