FROM public.ecr.aws/lambda/python:3.10

# Set lambda root as working directory
WORKDIR ${LAMBDA_TASK_ROOT}

# Selenium-related installs
RUN yum update -y \
    && yum clean all \
    && yum install -y tar gzip bzip2
RUN yum install xz atk cups-libs gtk3 libXcomposite alsa-lib \
    libXcursor libXdamage libXext libXi libXrandr libXScrnSaver \
    libXtst pango at-spi2-atk libXt xorg-x11-server-Xvfb \
    xorg-x11-xauth dbus-glib dbus-glib-devel -y -q
RUN rm -rf /var/cache/yum
COPY ./pipeline/install-firefox.sh .
RUN bash install-firefox.sh

# Grab requirement files
COPY ./case_fetcher/requirements.txt ./case_fetcher/
COPY ./gpt/requirements.txt ./gpt/
COPY ./judge_scraping/requirements.txt ./judge_scraping/
COPY ./xml_extraction/requirements.txt ./xml_extraction/
COPY ./pipeline/requirements.txt ./pipeline/

# Install all requirements
RUN yum install -y findutils
RUN find . -type f -name "requirements.txt" | sed -e 's/^/-r /' | xargs pip install

# Copy everything else
COPY ./case_fetcher ./case_fetcher/
COPY ./gpt ./gpt/
COPY ./judge_scraping ./judge_scraping/
COPY ./xml_extraction ./xml_extraction/
COPY ./pipeline ./pipeline/

CMD [ "pipeline.etl.handler" ]
