module "phase-one" {
    source = "./phase-one"
    ACCESS_KEY = var.ACCESS_KEY
    SECRET_ACCESS_KEY = var.SECRET_ACCESS_KEY
    REGION = var.REGION
    DB_NAME = var.DB_NAME
    DB_USERNAME = var.DB_USERNAME
    DB_PASSWORD = var.DB_PASSWORD
    VPC_ID = var.VPC_ID
    SUBNET_IDS = var.SUBNET_IDS

    DB_SUBNET_GROUP_NAME = var.DB_SUBNET_GROUP_NAME
    RDS_SECURITY_GROUP_NAME = var.RDS_SECURITY_GROUP_NAME
    COURTS_RDS_NAME = var.COURTS_RDS_NAME
    ECR_FOR_LAMBDA_NAME = var.ECR_FOR_LAMBDA_NAME
    ECR_FOR_EMAIL_NAME = var.ECR_FOR_EMAIL_NAME
    ECR_FOR_DASHBOARD_NAME = var.ECR_FOR_DASHBOARD_NAME
    ECR_FOR_API_NAME = var.ECR_FOR_API_NAME
}

module "phase-two" {
    source = "./phase-two"
    ACCESS_KEY = var.ACCESS_KEY
    SECRET_ACCESS_KEY = var.SECRET_ACCESS_KEY
    REGION = var.REGION
    DB_NAME = var.DB_NAME
    DB_USERNAME = var.DB_USERNAME
    DB_PASSWORD = var.DB_PASSWORD
    DB_HOST = var.DB_HOST
    DB_PORT = var.DB_PORT
    VPC_ID = var.VPC_ID
    SUBNET_IDS = var.SUBNET_IDS

    DASHBOARD_IMAGE_URI = var.DASHBOARD_IMAGE_URI
    PIPELINE_IMAGE_URI = var.PIPELINE_IMAGE_URI
    EMAIL_IMAGE_URI = var.EMAIL_IMAGE_URI
    API_IMAGE_URI = var.API_IMAGE_URI
    ECS_CLUSTER = var.ECS_CLUSTER
    OPENAI_API_KEY = var.OPENAI_API_KEY

    DASHBOARD_TASK_DEFINITION_NAME = var.DASHBOARD_TASK_DEFINITION_NAME
    DASHBOARD_SECURITY_GROUP_NAME = var.DASHBOARD_SECURITY_GROUP_NAME
    DASHBOARD_ECS_SERVICE_NAME = var.DASHBOARD_ECS_SERVICE_NAME
    API_TASK_DEFINITION_NAME = var.API_TASK_DEFINITION_NAME
    API_SECURITY_GROUP_NAME = var.API_SECURITY_GROUP_NAME
    API_ECS_SERVICE_NAME = var.API_ECS_SERVICE_NAME
    LAMBDA_EXEC_ROLE_NAME = var.LAMBDA_EXEC_ROLE_NAME
    PIPELINE_LAMBDA_NAME = var.PIPELINE_LAMBDA_NAME
    EMAIL_LAMBDA_NAME = var.EMAIL_LAMBDA_NAME
    ORIGIN_EMAIL = var.ORIGIN_EMAIL
    PIPELINE_SCHEDULER_ROLE_NAME = var.PIPELINE_SCHEDULER_ROLE_NAME
    PIPELINE_SCHEDULER_POLICY_NAME = var.PIPELINE_SCHEDULER_POLICY_NAME
    PIPELINE_SCHEDULER_NAME = var.PIPELINE_SCHEDULER_NAME
}