module "phase-one" {
    source = "./phase-one"
    ACCESS_KEY = var.ACCESS_KEY
    SECRET_ACCESS_KEY = var.SECRET_ACCESS_KEY
    REGION = var.REGION
    DB_NAME = var.DB_NAME
    DB_USERNAME = var.DB_USERNAME
    DB_PASSWORD = var.DB_PASSWORD
    VPC_ID = var.VPC_ID
    SUBNET_IDS = var.SUBNET_IDS

    DB_SUBNET_GROUP_NAME = var.DB_SUBNET_GROUP_NAME
    RDS_SECURITY_GROUP_NAME = var.RDS_SECURITY_GROUP_NAME
    COURTS_RDS_NAME = var.COURTS_RDS_NAME
    ECR_FOR_LAMBDA_NAME = var.ECR_FOR_LAMBDA_NAME
    ECR_FOR_ECS_NAME = var.ECR_FOR_ECS_NAME
    ECR_FOR_DASHBOARD_NAME = var.ECR_FOR_DASHBOARD_NAME
}

module "phase-two" {
    source = "./phase-two"
    ACCESS_KEY = var.ACCESS_KEY
    SECRET_ACCESS_KEY = var.SECRET_ACCESS_KEY
    REGION = var.REGION
    DB_NAME = var.DB_NAME
    DB_USERNAME = var.DB_USERNAME
    DB_PASSWORD = var.DB_PASSWORD
    DB_HOST = var.DB_HOST
    DB_PORT = var.DB_PORT
    VPC_ID = var.VPC_ID
    SUBNET_IDS = var.SUBNET_IDS

    DASHBOARD_IMAGE_URI = var.DASHBOARD_IMAGE_URI
    ECS_CLUSTER = var.ECS_CLUSTER
}