on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: "Python Quality Check"
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          find . -type f -name "requirements.txt" | sed -e 's/^/-r /' | xargs pip install

      - name: Run pylint
        run: |
          find . -type f -name "*.py" | xargs pylint --disable=I1101 --fail-under=9
          
  test:
    name: "Python Tests Check"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          find . -type f -name "requirements.txt" | sed -e 's/^/-r /' | xargs pip install

      - name: Run the tests
        run: |
          pytest .

      - name: Run coverage
        run: |
          pytest --cov-fail-under=60
